# Buildtionnary : https://github.com/agonkolgeci/Buildtionnary

min-players: 2
max-players: 16

scoreboard:
  name: "<green><b>Buildtionnary</b>"
  footer: "<yellow>nexus.agonkolgeci.com"

# Times in seconds
timers:
  start: 30
  build: 120
  finish: 10

waiting-room:
  x: 0.5
  y: 1.5
  z: 0.5
  yaw: 0.0
  pitch: 0.0

build-area:
  '1':
    x: 14.0
    y: 1.0
    z: 14.0
  '2':
    x: -14.0
    y: 25.0
    z: -14.0